export const EVT_FORM_TEMPLATES_SET_FROM_LOGIN = "FORM_TEMPLATES_SET_FROM_LOGIN";
export const EVT_FORM_TEMPLATES_NEW_ADDITION = "FORM_TEMPLATES_NEW_ADDITION";
export const EVT_FORM_TEMPLATES_SAVE_TEMPLATES = "FORM_TEMPLATES_SAVE_TEMPLATES";
export const EVT_FORM_TEMPLATES_DELETION = "FORM_TEMPLATES_DELETION";
