export const EVT_TEMPLATES_SET_FROM_LOGIN = "TEMPLATES_SET_FROM_LOGIN";
export const EVT_TEMPLATES_NEW_ADDITION = "TEMPLATES_NEW_ADDITION";
export const EVT_TEMPLATES_SAVE_TEMPLATES = "TEMPLATES_SAVE_TEMPLATES";
export const EVT_TEMPLATES_DELETION = "TEMPLATES_DELETION";
